#!/usr/bin/env python3
"""Materialize M0/B0/B1/B2 on the frozen reviewer1 development set.

M0 is generated by ``run_phase3_devset_m0.py``.  This script only consumes the
saved M0 artifacts, de-standardises them, and applies the audited offline
baselines with the same physical motion and sample-level noise.  It never
reruns the model and never overwrites an existing output directory.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
import sys
from types import SimpleNamespace
from typing import Any

import numpy as np
import torch
from smplx import SMPLX


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from motion_rep.baselines import build_b0, build_b1, build_b2  # noqa: E402
from scripts.run_phase2_baselines import _one_metrics, tensor_sha256  # noqa: E402


COMMANDS = (0.0, 5.0, 10.0)


def command_label(delta: float) -> str:
    return f"{int(delta):02d}deg" if float(delta).is_integer() else f"{delta:g}deg"


def _load_seed_artifacts(seed_root: Path, expected_ids: list[str]) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, list[str]]:
    batch_dirs = sorted((seed_root / "artifacts").glob("batch_*"))
    if not batch_dirs:
        raise FileNotFoundError(f"no M0 artifact batches under {seed_root}")
    official, raw, z0, ids = [], [], [], []
    for batch_dir in batch_dirs:
        manifest_path = batch_dir / "sample_noise_manifest.json"
        if not manifest_path.exists():
            raise FileNotFoundError(manifest_path)
        records = json.loads(manifest_path.read_text(encoding="utf-8"))["records"]
        ids.extend(str(record["sample_id"]) for record in records)
        official.append(torch.load(batch_dir / "m0_official_norm_batch.pt", weights_only=True, map_location="cpu"))
        raw.append(torch.load(batch_dir / "m0_raw_norm_batch.pt", weights_only=True, map_location="cpu"))
        z0.append(torch.load(batch_dir / "z0_replayed.pt", weights_only=True, map_location="cpu"))
    if ids != expected_ids:
        raise ValueError(f"M0 sample order mismatch: expected {expected_ids}, got {ids}")
    return torch.cat(official), torch.cat(raw), torch.cat(z0), ids


def _save_motion(path: Path, motion: torch.Tensor) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(motion.detach().cpu(), path)
    return tensor_sha256(motion)


def run(
    manifest_path: Path,
    input_json: Path,
    m0_root: Path,
    output_root: Path,
    mean_path: Path,
    std_path: Path,
    smplx_path: Path,
    seeds: tuple[int, ...] = (0, 1, 2),
) -> dict[str, Any]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("status") not in {"FROZEN", "FROZEN_SINGLE_REVIEW_OVERRIDE"}:
        raise ValueError("baseline run requires a frozen manifest")
    inputs = json.loads(input_json.read_text(encoding="utf-8"))
    expected_ids = [str(row["sample_id"]) for row in inputs]
    if len(expected_ids) != 20 or len(set(expected_ids)) != 20:
        raise ValueError("expected 20 unique development-set sample IDs")
    mean = torch.from_numpy(np.load(mean_path)).float()
    std = torch.from_numpy(np.load(std_path)).float()
    if output_root.exists():
        raise FileExistsError(output_root)
    output_root.mkdir(parents=True)
    model = SMPLX(model_path=str(smplx_path), gender="neutral", use_pca=False, num_betas=10, batch_size=100).eval()
    records: list[dict[str, Any]] = []
    for seed in seeds:
        official_norm, raw_norm, z0, ids = _load_seed_artifacts(m0_root / f"seed_{seed:03d}", expected_ids)
        if tuple(official_norm.shape) != (20, 100, 276):
            raise ValueError(f"unexpected official shape for seed {seed}: {tuple(official_norm.shape)}")
        physical_official = official_norm.float() * std + mean
        physical_raw = raw_norm.float() * std + mean
        seed_output = output_root / f"seed_{seed:03d}"
        seed_output.mkdir()
        for index, sample_id in enumerate(ids):
            motion = physical_official[index]
            raw_motion = physical_raw[index]
            valid = torch.ones(motion.shape[0], dtype=torch.bool)
            sample_dir = seed_output / f"sample_{sample_id}"
            sample_dir.mkdir()
            source_records = []
            source_records.append({
                "sample_id": sample_id,
                "seed": seed,
                "method": "M0_raw",
                "delta_deg": 0.0,
                "path": str(sample_dir / "M0_raw_delta00deg.pt"),
                "tensor_sha256": _save_motion(sample_dir / "M0_raw_delta00deg.pt", raw_motion),
                "source": "m0_raw_norm_batch.pt",
            })
            for method, method_motion in (("M0_official", motion),):
                for command in COMMANDS:
                    path = sample_dir / f"{method}_delta{command_label(command)}.pt"
                    source_records.append({
                        "sample_id": sample_id,
                        "seed": seed,
                        "method": method,
                        "delta_deg": command,
                        "path": str(path),
                        "tensor_sha256": _save_motion(path, method_motion),
                        "source": "m0_official_norm_batch.pt",
                    })
            b0 = build_b0(motion)
            for command in COMMANDS:
                path = sample_dir / f"B0_delta{command_label(command)}.pt"
                source_records.append({
                    "sample_id": sample_id,
                    "seed": seed,
                    "method": "B0",
                    "delta_deg": command,
                    "path": str(path),
                    "tensor_sha256": _save_motion(path, b0.motion),
                    "source": "build_b0(M0_official)",
                    "metrics": _one_metrics(model, SimpleNamespace(name="B0", motion=b0.motion, valid_mask=b0.valid_mask, diagnostics=b0.diagnostics)),
                })
            for method_name, builder in (("B1", build_b1), ("B2", build_b2)):
                for command in COMMANDS:
                    result = builder(motion, delta_deg=command, axis="x")
                    path = sample_dir / f"{method_name}_delta{command_label(command)}.pt"
                    source_records.append({
                        "sample_id": sample_id,
                        "seed": seed,
                        "method": method_name,
                        "delta_deg": command,
                        "path": str(path),
                        "tensor_sha256": _save_motion(path, result.motion),
                        "source": "build_baseline(M0_official)",
                        "metrics": _one_metrics(model, result),
                    })
            (sample_dir / "sample_record.json").write_text(json.dumps(source_records, indent=2) + "\n", encoding="utf-8")
            records.extend(source_records)
        torch.save(z0, seed_output / "z0_batch.pt")
        (seed_output / "z0_sha256.txt").write_text(tensor_sha256(z0) + "\n", encoding="utf-8")
    report = {
        "status": "VERIFIED_PHASE2_DEVSET_BASELINES",
        "manifest": str(manifest_path),
        "input": str(input_json),
        "m0_root": str(m0_root),
        "output_root": str(output_root),
        "target_units": 20 * len(seeds) * 3,
        "methods": ["M0_official", "B0", "B1", "B2"],
        "commands_degrees": list(COMMANDS),
        "seeds": list(seeds),
        "review_protocol": manifest.get("review_protocol"),
        "records": records,
        "notes": [
            "M0_official is the frozen model output; B0/B1/B2 consume the same de-standardised M0 official motion.",
            "B0 is intentionally identical across command labels because it has no edit.",
            "B1 is an intentionally inconsistent diagnostic baseline and is not ranked by foot/physical metrics.",
            "Axis x is the model-space probe convention; clinical/anatomical semantics remain PENDING.",
        ],
    }
    (output_root / "baseline_metrics.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--m0-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--mean", type=Path, default=Path("data/meta_info/mean.npy"))
    parser.add_argument("--std", type=Path, default=Path("data/meta_info/std.npy"))
    parser.add_argument("--smplx", type=Path, default=Path("data/body_models/smplx"))
    args = parser.parse_args()
    print(json.dumps(run(args.manifest, args.input, args.m0_root, args.output_root, args.mean, args.std, args.smplx), indent=2))


if __name__ == "__main__":
    main()
